# Site settings
title: MrFu-傅圆的个人博客
email: mrfuyuan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  我叫傅圆，我是一名 Android 开发者.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 15068728607
github_username:  mrfufufu

# Build settings
markdown: kramdown
